### ISSUE TITLE
Multiple reRECAPTCHA scripts

### ISSUE THREAD

**Issue by Moucky** [solspace/craft-freeform#267] opened 2022-02-03 03:03 UTC
It looks like there are multiple reCAPTCHA scripts and badges being added to the page when there is more than one form on the same page. Is this likely my templating or the plugin?

**Comment by kjmartens** [comment] 2022-02-03 15:38
Hi @Moucky,

I haven't heard of this issue happening before. Can you let me know which version of Freeform you have, what your template code looks like, etc? :)

**Comment by Moucky** [comment] 2022-02-10 22:13
Sorry, I forgot about this. I have version "3.12.12.1" of Freeform. I haven't tried looking at the template yet but wouldn't it be unlikely for the templates to impact this as it is automatically added down the bottom of the page?

**Comment by kjmartens** [comment] 2022-02-10 22:18
No problem @Moucky. The trouble is that I don't have a lot of information to go on here. I'll need to know other things to help build context about why this might be happening.

- It'd be great to see the live page and/or the template code for the page (this would potentially allow us to see what else is being loaded into the page)
- Are you using any other external service or form/plugin that might also be loading reCAPTCHA into the page? (e.g. a "Newsletter signup" form from a different plugin that is designed specifically for that)
- Do you have any other plugins that enable reCAPTCHA for Craft and/or have your own implementation of reCAPTCHA somewhere in the code?
- Are you caching the page or form in some way?

**Comment by Moucky** [comment] 2022-02-10 22:29
Thanks @kjmartens. I do not use any other services other than Freeform that would use reCAPTCHA however I do use the Freeform Mailchimp integration and I am not caching the pages. I will try to add more detail about the templates as soon as possible but it does appear as though each form on the page gets its own reCAPTCHA script added and therefore multiple badges show. The forms seem to be working fine though.

**Comment by Moucky** [comment] 2022-02-15 00:14
Is it possible for someone to have a look at this without me having to post my templates? Is it even possible for my templates to have an impact on how many scripts get added to the page? It's not like I edit any part of the template for that to happen.

**Comment by kjmartens** [comment] 2022-02-15 01:03
@Moucky I would need something else to go off of. I cannot duplicate this issue at all on my end, and have not heard of any other customer with this issue either. I'm not saying that Freeform for sure isn't at fault here, but I just don't know how else to reproduce the issue. Seeing your setup/templates would give me an idea if I need to adjust my setup in any way to reproduce the issue. 🙂 

You don't need to share anything publicly... you can [submit a private support ticket here](https://docs.solspace.com/craft/freeform/v3/support.html).

The best thing to do would be to create a new minimal template and include more than 1 form in it and see if the issue happens there as well. 🙂

**Comment by Moucky** [comment] 2022-02-15 01:07
OK @kjmartens, thanks for the response. I will have a look and see what I do!

**Comment by bengreenbank** [comment] 2022-05-26 19:54
No worries. Thanks for getting back to me!

Yes the issue seems to be fixed on our end too. It's been so long that I can't quite remember whether we implemented a fix or whether this has resolved itself.

I will let you know if we experience this again :)

**Closed** 2022-05-26 20:22 UTC
